# config/application-local.yaml
spring:
  datasource:
    # this covers the OpenMetadata API / metadata store
    url: jdbc:mysql://openmetadata-mysql:3306/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: openmetadata_user
    password-file: /run/secrets/om_mysql_pass

flowable:
  # override the Event Registry engine
  event:
    registry:
      datasource:
        url: jdbc:mysql://openmetadata-mysql:3306/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: openmetadata_user
        password-file: /run/secrets/om_mysql_pass

  # override the IDM (identity) engine
  idm:
    datasource:
      url: jdbc:mysql://openmetadata-mysql:3306/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      username: openmetadata_user
      password-file: /run/secrets/om_mysql_pass
