flowable:
  event:
    registry:
      datasource:
        url: "jdbc:mysql://openmetadata-mysql:3306/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
        username: openmetadata_user
        password: /run/secrets/om_mysql_pass
  process:
    datasource:
      url: "jdbc:mysql://openmetadata-mysql:3306/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
      username: openmetadata_user
      password: /run/secrets/om_mysql_pass
