# openmetadata_ingestion_scripts/mongodb_connector_config.yaml
# This YAML configuration defines the workflow for ingesting metadata from MongoDB
# into OpenMetadata. It will scan databases and collections, including their schemas.

source:
  type: mongodb
  serviceName: my_mongodb_db # Name of the MongoDB service in OpenMetadata
  serviceConnection:
    config:
      type: MongoDB # Type of connection configuration
      username: root # MongoDB user from docker-compose
      password: password # MongoDB password from docker-compose
      # IMPORTANT NOTE: 'mongodb' is the service name from docker-compose.
      hostPort: mongodb:27017
      authSource: admin # Specify the authentication database if needed (root user is in admin db)
  sourceConfig:
    config:
      type: DatabaseMetadata # Type of source config for database metadata
      # databaseFilterPattern:
      #   includes:
      #     - my_data_platform_db # Include specific databases
      #     - dynamic_insurance_data
      # schemaFilterPattern: # For MongoDB, this usually refers to databases
      #   includes:
      #     - my_data_platform_db
processor:
  type: om-metadata-processor
  config: {}
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: http://openmetadata-server:8585
    authProvider: no-auth
