services:
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr"
      - ":8181"
      - "--log-level"
      - "debug"
    networks:
      - data_platform_network
    healthcheck:
      test: ["CMD-SHELL", "sh -c '</dev/tcp/localhost/8181'"]
      interval: 10s
      timeout: 5s
      retries: 5
