services:
  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=airflow # Reusing the airflow user for simplicity in this lab
      - POSTGRES_PWD=airflow
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    depends_on:
      - postgres
    networks:
      - data_platform_network

  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    ports:
      - "8082:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal
    networks:
      - data_platform_network
