# prometheus.yml
# This is the Prometheus configuration file used by the 'prometheus' service in docker-compose.yml.
# It defines targets for Prometheus to scrape metrics from.

global:
  # The scrape interval is how often Prometheus will scrape targets
  scrape_interval: 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'data-platform-monitor'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus's own metrics

  # Scrape metrics from the FastAPI ingestor
  - job_name: 'fastapi_ingestor'
    # FastAPI's metrics path, assuming OpenTelemetry instrumentation
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi_ingestor:8000'] # Docker Compose service name and port

  # Scrape metrics from cAdvisor (container resource usage)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] # Docker Compose service name and internal port

  # (Optional) Example: Scrape Grafana Alloy's internal metrics
  # If you want Prometheus to also scrape Alloy's own metrics endpoint
  - job_name: 'grafana_alloy'
    static_configs:
      - targets: ['grafana_alloy:12345'] # The port Alloy exposes its own metrics on

  # (Optional) Example: Scrape Kafka JMX Exporter
  # If you later add a Kafka JMX Exporter sidecar, configure it here.
  # - job_name: 'kafka-jmx'
  #   static_configs:
  #     - targets: ['kafka-jmx-exporter:8080']

  # (Optional) Example: Scrape PostgreSQL Exporter
  # If you later add a PostgreSQL exporter, configure it here.
  # - job_name: 'postgres-exporter'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
